software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: bionic-unstable
    production: bionic-stable

jobs:
  python-aws:
    builder: "make"
    software_groups: *software
    base: "quay.io/madebymany/build-bases:bionic"
    packages:
      - type: debian
        name: python-aws
        depends:
          - python-pip
        repos:
          - mxm-public
        target: install
