software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  python-aws:
    builder: "make"
    software_groups: *software
    base: "ubuntu:12.04"
    packages:
      - type: debian
        name: python-aws
        version: 1.5.2
        depends:
          - python-pip
        repos:
          - mxm-public
        target: install
