software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: focal-unstable
    production: focal-stable

jobs:
  python-aws:
    builder: "make"
    software_groups: *software
    base: "quay.io/madebymany/build-bases:focal"
    packages:
      - type: debian
        name: python-aws
        depends:
          - python-pip
        repos:
          - mxm-public
        target: install
